name: Android CI

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: set up JDK 1.8
      uses: actions/setup-java@main
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: chmod 777 ./gradlew && ./gradlew :app:assemble && find app/build/outputs
    - name: Upload apk
      uses: actions/upload-artifact@main
      with:
        name: app-armeabi-v7a-release-unsigned.apk
        path: app/build/outputs/apk/common/
