name: Android CI

on: [push,workflow_dispatch]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      # 1) checkout 最新 action
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2) 安装 JDK（使用 Temurin，启用 gradle 缓存）
      - name: Set up JDK (Temurin 8) and enable Gradle cache
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '8'           # 与原来的 JDK 1.8 对应
          cache: 'gradle'
          cache-dependency-path: |
            **/build.gradle*
            **/gradle-wrapper.properties

      # 3) 运行 gradle 构建（授权 gradlew）
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          # 根据你的构建目标选择 assembleRelease/assembleDebug 或具体的变体
          ./gradlew :app:assembleRelease --no-daemon --stacktrace
          echo "Built outputs:"
          find app/build/outputs -type f -name "*.apk" -print || true

      # 4) 上传 APK（使用 v4，可用通配符并在未找到文件时报错）
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: app/build/outputs/**/*.apk
          if-no-files-found: error
          retention-days: 7
